//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace funko_store_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios
    {
        public string idusu { get; set; }
        public string nomusu { get; set; }
        public string pass { get; set; }
        public string tipusu { get; set; }
        public string correo { get; set; }
        public string direcenvio { get; set; }
        public string tarjeta { get; set; }
        public string estado { get; set; }
    }
}
